#include $(TOPLEVEL)/.config

dirs-y :=
obj-y := Region.o \
	RegionCommon.o \
	RegionCN470.o \
	RegionCN470A20.o \
	RegionCN470A26.o \
	RegionCN470B20.o \
	RegionCN470B26.o \
	RegionBaseUS.o

include $(TOPLEVEL)/Makefile.rules
