#include $(TOPLEVEL)/.config

dirs-y :=
obj-y := LoRaMac.o \
	LoRaMacAdr.o \
	LoRaMacCommands.o \
	LoRaMacConfirmQueue.o \
	LoRaMacCrypto.o \
	LoRaMacParser.o \
	LoRaMacSerializer.o \
	LoRaMacClassB.o

include $(TOPLEVEL)/Makefile.rules
